// Sourced verbatim from the C2PA Technical Specification, "Standard Status Codes"
// (https://spec.c2pa.org/specifications/specifications/2.1/specs/C2PA_Specification.html#_standard_status_codes,
// extracted from the 2.4 spec build). Do not hand-edit; these are the spec's own
// definitions for validation_results codes, not inferred/reverse-engineered behavior.

export type StatusCategory = "success" | "informational" | "failure";

export type StatusCodeEntry = {
  code: string;
  meaning: string;
};

export const STATUS_CODES: Record<StatusCategory, StatusCodeEntry[]> = {
  success: [
    { code: "assertion.accessible", meaning: "A non-embedded (remote) assertion was accessible at the time of validation." },
    { code: "assertion.bmffHash.match", meaning: "Hash of a box-based asset matches the hash declared in the BMFF hash assertion." },
    { code: "assertion.boxesHash.match", meaning: "Hash of a box-based asset matches the hash declared in the general box hash assertion." },
    { code: "assertion.collectionHash.match", meaning: "Hashes of all the assets contained in a collection matches the hashes declared in the collection data hash assertion." },
    { code: "assertion.dataHash.match", meaning: "Hash of a byte range of the asset matches the hash declared in the data hash assertion." },
    { code: "assertion.hashedURI.match", meaning: "The hash of the referenced assertion matches the corresponding hash in the assertion’s hashed URI in the claim." },
    { code: "assertion.multiAssetHash.match", meaning: "The hash of one part of a multi-asset hash assertion matches the corresponding hash in the assertion’s multi-asset-hash-map." },
    { code: "assertion.alternativeContentRepresentation.match", meaning: "The original preservation image assertion and its associated content validated successfully." },
    { code: "claimSignature.insideValidity", meaning: "The claim signature referenced in the claim was created within the validity period of the signing credential" },
    { code: "claimSignature.validated", meaning: "The claim signature referenced in the claim validated." },
    { code: "ingredient.claimSignature.validated", meaning: "The hash of the ingredient’s C2PA Claim Signature box was successfully validated." },
    { code: "ingredient.manifest.validated", meaning: "The hash of the ingredient’s C2PA Manifest box was successfully validated." },
    { code: "signingCredential.ocsp.notRevoked", meaning: "The signing credential was not revoked at the time of signing." },
    { code: "signingCredential.trusted", meaning: "The signing credential is trusted" },
    { code: "timeStamp.trusted", meaning: "The time-stamp credential is listed on the validator’s list of trust anchors for time stamping authorities ." },
    { code: "timeStamp.validated", meaning: "The time-stamp is well-formed, has a message imprint that matches the Claim Signature, and was created within the validity period of the time-stamp credential." },
  ],
  informational: [
    { code: "algorithm.deprecated", meaning: "The algorithm has been deprecated." },
    { code: "assertion.bmffHash.additionalExclusionsPresent", meaning: "A BMFF hash specified exclusion ranges other than the C2PA Manifest Store." },
    { code: "assertion.boxesHash.additionalExclusionsPresent", meaning: "A box hash specified exclusion ranges other than the C2PA Manifest Store." },
    { code: "assertion.dataHash.additionalExclusionsPresent", meaning: "A data hash specified exclusion ranges other than the C2PA Manifest Store." },
    { code: "ingredient.unknownProvenance", meaning: "The ingredient does not have a C2PA Manifest." },
    { code: "signingCredential.ocsp.inaccessible", meaning: "The validator attempted to perform an online OCSP check, but did not receive a response." },
    { code: "signingCredential.ocsp.skipped", meaning: "The validator chose not to perform an online OCSP check." },
    { code: "signingCredential.ocsp.unknown", meaning: "The OCSP response contains an unknown status for the signing credential" },
    { code: "timeOfSigning.insideValidity", meaning: "The claimed time of signing (in the iat header of the signature) is within the validity period of the signer’s certificate chain and before the time in any corresponding trusted time-stamp." },
    { code: "timeOfSigning.outsideValidity", meaning: "The claimed time of signing (in the iat header of the signature) is outside the validity period of the signer’s certificate chain or later than the time in a corresponding trusted time-stamp." },
    { code: "timeStamp.credentialInvalid", meaning: "The time-stamp credential is invalid." },
    { code: "timeStamp.malformed", meaning: "The time-stamp response included in the claim signature header is not properly formed, as per RFC 3161" },
    { code: "timeStamp.mismatch", meaning: "The time-stamp does not correspond to the contents of the claim." },
    { code: "timeStamp.outsideValidity", meaning: "The signed time-stamp attribute in the signature was created outside the validity period of the TSA’s certificate." },
    { code: "timeStamp.untrusted", meaning: "The time-stamp credential is not listed on the validator’s TSA trust lists ." },
  ],
  failure: [
    { code: "algorithm.unsupported", meaning: "The algorithm is unspecified or unsupported." },
    { code: "assertion.action.ingredientMismatch", meaning: "An action that requires an associated ingredient either does not have one or the one specified cannot be located" },
    { code: "assertion.action.malformed", meaning: "An actions assertion is malformed." },
    { code: "assertion.action.redacted", meaning: "An actions assertion was redacted when the claim was created." },
    { code: "assertion.action.redactionMismatch", meaning: "An action that requires an associated redaction either does not have one or the one specified cannot be located" },
    { code: "assertion.action.softBindingMissing", meaning: "An action that requires an associated soft binding does not have one" },
    { code: "assertion.bmffHash.malformed", meaning: "A BMFF hash assertion is malformed." },
    { code: "assertion.bmffHash.mismatch", meaning: "The hash of a box-based asset does not match the hash declared in a BMFF hash assertion." },
    { code: "assertion.boxesHash.malformed", meaning: "The general box hash assertion is malformed." },
    { code: "assertion.boxesHash.mismatch", meaning: "The hash of a general box-like asset format does not match the hash declared in a general box hash assertion." },
    { code: "assertion.boxesHash.unknownBox", meaning: "A box other than those expected was found" },
    { code: "assertion.cbor.invalid", meaning: "The cbor of an assertion is not valid" },
    { code: "assertion.cloud-data.actions", meaning: "An update manifest contains a cloud data assertion referencing an actions assertion." },
    { code: "assertion.cloud-data.hardBinding", meaning: "A hard binding assertion is in a cloud data assertion." },
    { code: "assertion.cloud-data.malformed", meaning: "The cloud-data assertion was incomplete" },
    { code: "assertion.cloud-data.labelMismatch", meaning: "The label of the JUMBF box retrieved from the cloud data assertion does not match the expected label." },
    { code: "assertion.collectionHash.incorrectFileCount", meaning: "An asset that was listed in the collection data hash assertion is missing from the collection." },
    { code: "assertion.collectionHash.invalidURI", meaning: "A URI of an asset in the collection data hash assertion contains the file part '..' or '.'." },
    { code: "assertion.collectionHash.malformed", meaning: "The collection hash assertion was incomplete" },
    { code: "assertion.collectionHash.mismatch", meaning: "A hash of an asset in the collection does not match hash declared in the collection data hash assertion." },
    { code: "assertion.dataHash.malformed", meaning: "A data hash assertion is malformed." },
    { code: "assertion.dataHash.mismatch", meaning: "The hash of a byte range of the asset does not match the hash declared in the data hash assertion." },
    { code: "assertion.dataHash.redacted", meaning: "(DEPRECATED) A hard binding assertion was redacted." },
    { code: "assertion.external-reference.created", meaning: "The external reference assertion was present in the list of created assertions" },
    { code: "assertion.external-reference.hashMismatch", meaning: "The hash of retrieved data does not match the hash declared in the location field of a hashed external reference" },
    { code: "assertion.external-reference.labelMismatch", meaning: "The label of the JUMBF box retrieved from the external reference assertion does not match the expected label." },
    { code: "assertion.external-reference.malformed", meaning: "The external reference assertion was incomplete" },
    { code: "assertion.hardBinding.redacted", meaning: "A hard binding assertion was redacted." },
    { code: "assertion.hashedURI.mismatch", meaning: "The hash of the the referenced assertion in the manifest does not match the corresponding hash in the assertion’s hashed URI in the claim." },
    { code: "assertion.inaccessible", meaning: "A non-embedded (remote) assertion was inaccessible at the time of validation." },
    { code: "assertion.ingredient.malformed", meaning: "The ingredient assertion was incomplete" },
    { code: "assertion.json.invalid", meaning: "The JSON(-LD) of an assertion is not valid" },
    { code: "assertion.missing", meaning: "An assertion listed in the manifest’s claim is missing from the asset’s manifest." },
    { code: "assertion.multiAssetHash.malformed", meaning: "A multi-asset hash assertion is malformed." },
    { code: "assertion.multiAssetHash.missingPart", meaning: "A required part of the multi-part asset cannot be located." },
    { code: "assertion.multiAssetHash.mismatch", meaning: "The hash of a part of a multi-part asset does not match the hash declared in the mutli-asset hash assertion." },
    { code: "assertion.alternativeContentRepresentation.malformed", meaning: "The original preservation image assertion is malformed or contains invalid fields (e.g., both boxes and url fields are present, or invalid target usage)." },
    { code: "assertion.alternativeContentRepresentation.hashMismatch", meaning: "The hash of the original preservation image content does not match the hash declared in the assertion." },
    { code: "assertion.alternativeContentRepresentation.missing", meaning: "The original preservation image assertion, or its required content, could not be found or resolved." },
    { code: "assertion.multipleHardBindings", meaning: "The manifest has more than one hard binding assertion." },
    { code: "assertion.notRedacted", meaning: "An assertion was declared as redacted in the claim but is still present in the manifest." },
    { code: "assertion.outsideManifest", meaning: "An assertion listed in the claim is not in the same C2PA Manifest as the claim" },
    { code: "assertion.selfRedacted", meaning: "An assertion was declared as redacted by its own claim." },
    { code: "assertion.timestamp.malformed", meaning: "The time-stamp assertion is malformed." },
    { code: "assertion.undeclared", meaning: "An assertion was found in the manifest that was not explicitly declared in the claim." },
    { code: "claim.cbor.invalid", meaning: "The cbor of the claim is not valid." },
    { code: "claim.hardBindings.missing", meaning: "No hard bindings are present." },
    { code: "claim.malformed", meaning: "The data/fields of the referenced claim in the manifest are not correct." },
    { code: "claim.missing", meaning: "The referenced claim in the manifest cannot be found." },
    { code: "claim.multiple", meaning: "More than one claim box is present in the manifest." },
    { code: "claimSignature.missing", meaning: "The claim signature referenced in the claim cannot be found in its manifest." },
    { code: "claimSignature.mismatch", meaning: "The claim signature referenced in the claim failed to validate." },
    { code: "claimSignature.outsideValidity", meaning: "The claim signature referenced in the claim was created outside the validity period of the signing credential." },
    { code: "general.error", meaning: "A value to be used when there was an error not specifically listed here." },
    { code: "hashedURI.missing", meaning: "The data pointed to by a hashed_uri cannot be located" },
    { code: "hashedURI.mismatch", meaning: "The hash of a given hashed_uri does not match the corresponding hash of the destination URI’s data" },
    { code: "ingredient.claimSignature.missing", meaning: "The referenced ingredient C2PA Claim Signature was not found." },
    { code: "ingredient.claimSignature.mismatch", meaning: "The hash of an embedded C2PA Manifest’s C2PA Claim Signature does not match the hash declared in the hashed_uri value of the claimSignature field in the ingredient assertion." },
    { code: "ingredient.manifest.missing", meaning: "The referenced ingredient C2PA Manifest was not found." },
    { code: "ingredient.manifest.mismatch", meaning: "The hash of an embedded C2PA Manifest does not match the hash declared in the hashed_uri value of the activeManifest field in the ingredient assertion." },
    { code: "livevideo.assertion.invalid", meaning: "The assertion is not valid due to sequenceNumber , streamId mismatch." },
    { code: "livevideo.continuityMethod.invalid", meaning: "The continuityMethod is invalid or not recognized." },
    { code: "livevideo.init.invalid", meaning: "The init segment is not valid, improperly contains a mdat box." },
    { code: "livevideo.manifest.invalid", meaning: "The manifest failed validation." },
    { code: "livevideo.segment.invalid", meaning: "The segment is not valid, (1) it contains neither a valid emsg box nor C2PA Manifest Box, (2) no valid session keys, (3) the emsg signature fails signature validation, or (4) the previousManifestId didn’t match the previous manifest." },
    { code: "livevideo.sessionkey.invalid", meaning: "The session key is not valid, (1) does not meet requirements for session keys, (2) signerBinding doesn’t validate, or (3) the Claim Generator’s certificate used to protect delivery of the session key has expired." },
    { code: "manifest.compressed.invalid", meaning: "The compressed manifest was not valid." },
    { code: "manifest.html.multipleManifests", meaning: "More than one C2PA manifest element was found in the HTML document." },
    { code: "manifest.inaccessible", meaning: "A non-embedded (remote) manifest was inaccessible at the time of validation." },
    { code: "manifest.multipleParents", meaning: "The manifest has more than one ingredient whose relationship is parentOf ." },
    { code: "manifest.structuredText.emptyReference", meaning: "A structured text manifest block was found but the manifest reference between the delimiters is empty or contains only whitespace." },
    { code: "manifest.structuredText.malformedReference", meaning: "A structured text manifest block was found but the manifest reference is not a valid URL or data: URI." },
    { code: "manifest.structuredText.multipleReferences", meaning: "More than one C2PA manifest block was found in the structured text file." },
    { code: "manifest.structuredText.noManifest", meaning: "The structured text file does not contain a valid manifest block (no delimiters found, or only one delimiter found)." },
    { code: "manifest.structuredText.noResolutionPath", meaning: "A structured text manifest block was found but no manifest resolution path could be determined." },
    { code: "manifest.timestamp.invalid", meaning: "The manifest is a time-stamp manifest, but it contains a disallowed (non-ingredient) assertion." },
    { code: "manifest.timestamp.wrongParents", meaning: "The manifest is an time-stamp manifest, but it contains either zero or multiple parentOf ingredients." },
    { code: "manifest.text.corruptedWrapper", meaning: "A C2PATextManifestWrapper magic number was detected, but the wrapper itself was malformed or incomplete." },
    { code: "manifest.text.multipleWrappers", meaning: "More than one valid C2PATextManifestWrapper was found in the text." },
    { code: "manifest.update.invalid", meaning: "The manifest is an update manifest, but it contains a disallowed assertion, such as a hard binding or actions assertions." },
    { code: "manifest.update.wrongParents", meaning: "The manifest is an update manifest, but it contains either zero or multiple parentOf ingredients." },
    { code: "signingCredential.invalid", meaning: "The signing credential is not valid for signing." },
    { code: "signingCredential.ocsp.revoked", meaning: "The OCSP response indicates that the signing credential has been revoked by the issuer." },
    { code: "signingCredential.untrusted", meaning: "The signing credential is not listed on any of the validator’s applicable trust lists ." },
  ],
};

const CODE_LOOKUP: Map<string, { category: StatusCategory; meaning: string }> = new Map();
for (const category of Object.keys(STATUS_CODES) as StatusCategory[]) {
  for (const entry of STATUS_CODES[category]) {
    CODE_LOOKUP.set(entry.code, { category, meaning: entry.meaning });
  }
}

export function lookupStatusCode(code: string): { category: StatusCategory; meaning: string } | null {
  return CODE_LOOKUP.get(code) ?? null;
}
